# config/secrets.yml
# Project Lima - Secrets (KEEP PRIVATE)

aws_access_key_id: "AKIAXXXXXXXXXXXXX"
aws_secret_access_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
database_password: "your-db-password"
openai_api_key: "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
